<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INHL1399" failures="3" tests="19" name="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" time="2.816" errors="0" timestamp="2023-03-21T17:53:20 IST" skipped="0">
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineInJoboffer_ValidExternalBusinessID" time="1.564"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineInDraftJoboffer_ValidExternalBusinessID" time="0.078"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineInDraftJoboffertopPlaceOnMarket_ValidExternalBusinessID" time="0.080"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineInUpdatedJobOffer_ValidExternalBusinessID" time="0.078"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimeSupportingDocumentAddedJobOffer_ValidExternalBusinessID" time="0.071"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimeSupportingDocumentRemovedJobOffer_ValidExternalBusinessID" time="0.076"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineWithdrawnJobOffer_ValidExternalBusinessID" time="0.081"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineQuestion_JobOffer_ValidExternalBusinessID" time="0.080"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineDeclineJobOffer_ValidExternalBusinessID" time="0.076"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineParticipatWithdrawnJobOffer_ValidExternalBusinessID" time="0.074"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineParticipatAwardedJobOffer_ValidExternalBusinessID" time="0.073"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineParticipatQAClosedJobOffer_ValidExternalBusinessID" time="0.064"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineOfferClosedJobOffer_ValidExternalBusinessID" time="0.066"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineParticipantCommittedJobOffer_ValidExternalBusinessID" time="0.085"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineexpiredJobOffer_ValidExternalBusinessID" time="0.069"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineUpdatedJobsJobOffer_ValidExternalBusinessID" time="0.050">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest.GetActivityTimelineUpdatedJobsJobOffer_ValidExternalBusinessID(Get_ActivityTimelineInJoboffer_API_apitest.java:234)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- GetActivityTimelineUpdatedJobsJobOffer_ValidExternalBusinessID -->
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineJobUpdatedJobOffer_ValidExternalBusinessID" time="0.041">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest.GetActivityTimelineJobUpdatedJobOffer_ValidExternalBusinessID(Get_ActivityTimelineInJoboffer_API_apitest.java:248)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- GetActivityTimelineJobUpdatedJobOffer_ValidExternalBusinessID -->
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineStartFieldWorkJobOffer_ValidExternalBusinessID" time="0.045">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest.GetActivityTimelineStartFieldWorkJobOffer_ValidExternalBusinessID(Get_ActivityTimelineInJoboffer_API_apitest.java:261)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- GetActivityTimelineStartFieldWorkJobOffer_ValidExternalBusinessID -->
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest" name="GetActivityTimelineDeleetdJobOffer_ValidExternalBusinessID" time="0.065"/>
  <system-out/>
</testsuite> <!-- org.pineapple.testscripts.Get_ActivityTimelineInJoboffer_API_apitest -->
